import * as React from 'react'

import { cn } from '@/lib/utils'

/*
 * Generated by `npx shadcn@latest add breadcrumb` (CLI 4.19.0, 2026-08-27),
 * then reconciled to this repository's rules. Three changes from what the
 * generator emits, all recorded in research.md D14:
 *
 *   1. `lucide-react` is not installed. Principle II names "icons as a package"
 *      among the dependencies that MUST NOT be added, and the two icons this
 *      file imported are eleven lines of SVG. Measured cost of keeping the
 *      package would have been 0.52 KB gzipped; the rule is the reason.
 *   2. BreadcrumbPage no longer carries `role="link" aria-disabled="true"`.
 *      contracts/cv-navigation.md requires the current page to not be a link,
 *      and a disabled link is still announced as a link (FR-069).
 *   3. `radix-ui` is not installed either. The generator imports it for one
 *      thing: a Slot backing `asChild` on BreadcrumbLink. Nothing in this
 *      repository passes `asChild` — there is no routing library to hand the
 *      anchor to, because every route here is a real document and navigation
 *      is a plain link. Removing it measured 1.04 KB gzipped, which is a small
 *      number and not the reason: Principle II's first rung is "does this need
 *      to exist at all", and a dependency carried for a prop no caller uses
 *      fails it whatever it weighs.
 *   4. Quote and semicolon style follow this repository, not the generator's.
 *
 * Every class name here resolves through the shadcn variable mapping in
 * styles/tokens.css. No literal colour enters this file (Principle VI).
 */

function ChevronRight({ className }: { className?: string }) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}

function MoreHorizontal({ className }: { className?: string }) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <circle cx="12" cy="12" r="1" />
      <circle cx="19" cy="12" r="1" />
      <circle cx="5" cy="12" r="1" />
    </svg>
  )
}

function Breadcrumb({ ...props }: React.ComponentProps<'nav'>) {
  return <nav data-slot="breadcrumb" {...props} />
}

function BreadcrumbList({ className, ...props }: React.ComponentProps<'ol'>) {
  return (
    <ol
      data-slot="breadcrumb-list"
      className={cn(
        'flex flex-wrap items-center gap-1.5 text-sm break-words text-muted-foreground sm:gap-2.5',
        className,
      )}
      {...props}
    />
  )
}

function BreadcrumbItem({ className, ...props }: React.ComponentProps<'li'>) {
  return (
    <li
      data-slot="breadcrumb-item"
      className={cn('inline-flex items-center gap-1.5', className)}
      {...props}
    />
  )
}

function BreadcrumbLink({ className, ...props }: React.ComponentProps<'a'>) {
  return (
    <a
      data-slot="breadcrumb-link"
      className={cn('transition-colors hover:text-foreground', className)}
      {...props}
    />
  )
}

/** The current page. Not a link, and marked so programmatically (FR-069, FR-075). */
function BreadcrumbPage({ className, ...props }: React.ComponentProps<'span'>) {
  return (
    <span
      data-slot="breadcrumb-page"
      aria-current="page"
      className={cn('font-normal text-foreground', className)}
      {...props}
    />
  )
}

function BreadcrumbSeparator({ children, className, ...props }: React.ComponentProps<'li'>) {
  return (
    <li
      data-slot="breadcrumb-separator"
      role="presentation"
      aria-hidden="true"
      className={cn('[&>svg]:size-3.5', className)}
      {...props}
    >
      {children ?? <ChevronRight />}
    </li>
  )
}

function BreadcrumbEllipsis({ className, ...props }: React.ComponentProps<'span'>) {
  return (
    <span
      data-slot="breadcrumb-ellipsis"
      role="presentation"
      aria-hidden="true"
      className={cn('flex size-9 items-center justify-center', className)}
      {...props}
    >
      <MoreHorizontal className="size-4" />
      <span className="visually-hidden">More</span>
    </span>
  )
}

export {
  Breadcrumb,
  BreadcrumbList,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbPage,
  BreadcrumbSeparator,
  BreadcrumbEllipsis,
}
